#pragma once

#include <Windows.h>

INT_PTR CALLBACK DlgProcAnnotateOptions(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcBlockInsert(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcDrawOptions(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcEditOps(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcEditTrap_CommandsQuery(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFileBlock(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcFileManage(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcFileShadow(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFileTracing(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcFixupOptions(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcGetLayerName(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcHomePointGo(HWND hDlg, UINT nMsg, WPARAM wParam, LPARAM);
INT_PTR CALLBACK DlgProcHomePointSet(HWND hDlg, UINT nMsg, WPARAM wParam, LPARAM);
INT_PTR CALLBACK DlgProcLPDOptions(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcModeLetter(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcModeRevise(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcPipeOptions(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcPipeSymbol(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcProjAxonometric(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcProjIsometric(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcProjOblique(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcProjPerspective(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcRLPDOptions(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetPasteLoc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupConstraints(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupConstraintsAxis(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupHatch(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupMouse_Buttons(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupNote(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupPenColor(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcSetupPenStyle(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcTrapFilter(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcTrapModify(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcUnits(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcViewLighting(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK DlgProcViewParameters(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcViewZoom(HWND, UINT, WPARAM, LPARAM);

double	DlgBoxGetItemDouble(HWND hDlg, int iCtrlId);
double	DlgBoxGetItemUnitsText(HWND hDlg, int iCtrlId);
void	DlgBoxSetItemDouble(HWND hDlg, int iCtrlId, double dVal);
void	DlgBoxSetItemUnitsText(HWND hDlg, int iCtrlId, double dVal);
