#pragma once

// Prototypes for all procedure called directly by Windows

// Dialog procedures

BOOL CALLBACK DlgProcAnnotateOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcBlockInsert(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcDrawOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcEditOps(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcEditTrap_CommandsQuery(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFileBlock(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFileManage(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFileShadow(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFileTracing(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcFixupOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcGetLayerName(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcHomePointGo(HWND hDlg, UINT nMsg, WPARAM wParam, LPARAM);
BOOL CALLBACK DlgProcHomePointSet(HWND hDlg, UINT nMsg, WPARAM wParam, LPARAM);
BOOL CALLBACK DlgProcSetupPenStyle(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcLPDOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcModeLetter(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcModeRevise(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcPipeOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcPipeSymbol(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcProjAxonometric(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcProjIsometric(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcProjOblique(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcProjPerspective(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcRLPDOptions(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetPasteLoc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetupConstraints(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetupConstraintsAxis(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetupHatch(HWND, UINT, WPARAM , LPARAM);
BOOL CALLBACK DlgProcSetupMouse_Buttons(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetupNote(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcSetupPenColor(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcTrapFilter(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcTrapModify(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcUnits(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcViewLighting(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcViewParameters(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProcViewZoom(HWND, UINT, WPARAM, LPARAM);

double	DlgBoxGetItemDouble(HWND hDlg, int iCtrlId);
double	DlgBoxGetItemUnitsText(HWND hDlg, int iCtrlId);
void	DlgBoxSetItemDouble(HWND hDlg, int iCtrlId, double dVal);
void	DlgBoxSetItemUnitsText(HWND hDlg, int iCtrlId, double dVal);
