//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PegAEsys.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   101
#define IDR_PEGAESYSTYPE                102
#define IDR_PEGSTROKEFONT               105
#define IDR_LAYER                       106
#define IDR_WINDOW                      107
#define IDR_TRAP                        108
#define IDD_SETUP_COLOR                 112
#define IDD_UNITS                       113
#define IDD_FILE_BLOCK                  114
#define IDD_SETUP_PENSTYLE              115
#define IDD_SET_LENGTH                  116
#define IDD_SUBPROC_PIPE_SYMBOL         117
#define IDD_SUBPROC_PIPE_OPTIONS        118
#define IDD_SETUP_CONSTRAINTS_AXIS      119
#define IDD_SETUP_CONSTRAINTS_GRID      120
#define IDD_PROJ_OBLIQUE                121
#define IDD_PROJ_AXONOMETRIC            122
#define IDD_PROJ_ISOMETRIC              123
#define IDD_PROJ_PERSPECTIVE            124
#define IDD_TRACING_EX                  125
#define IDD_DLGPROC_LPD_OPTIONS         126
#define IDD_SETUP_NOTE                  128
#define IDD_SET_TEXT                    129
#define IDD_ANNOTATE_OPTIONS            130
#define IDD_EDIT_TRAPCOMMANDS_QUERY     131
#define IDD_FIXUP_OPTIONS               132
#define IDD_HOME_POINT_EDIT             133
#define IDD_SET_ANGLE                   134
#define IDD_SETUP_HATCH                 135
#define IDD_TRAP_MODIFY                 136
#define IDD_HOME_POINT_GO               137
#define IDD_TRAP_FILTER                 138
#define IDD_DLGPROC_RLPD_OPTIONS        139
#define IDD_VIEWLIGHTING                140
#define IDD_INSERT_BLOCK                142
#define IDD_VIEWPARAMS                  143
#define IDD_PASTE_POSITION              144
#define IDD_MOUSEKEYS                   145
#define IDD_DRAW_OPTIONS                146
#define IDD_GET_LAYER_NAME              147
#define IDD_SET_SCALE                   148
#define IDD_FILE_MANAGE                 149
#define IDD_ADD_NOTE                    150
#define IDD_EDIT_OPTIONS                151
#define IDD_VIEW_ZOOM                   152
#define ID_SHEETSETUP_FORMFACTOR        156
#define ID_BACKGROUNDIMAGE_LOAD         157
#define ID_BACKGROUNDIMAGE_REMOVE       158
#define ID_VIEW_BACKGROUNDIMAGE         159
#define ID_VIEW_MODEINFORMATION         160
#define ID_FILE_PRINT161                161
#define ID_FILE_PAGESETUP               162
#define IDD_DIALOG1                     163
#define IDD_PRINT_EX                    163
#define IDR_MENU1                       164
#define IDR_TRACING                     164
#define IDD_DIALOG2                     171
#define IDD_SET_MARK_STYLE              172
#define IDC_ENGINEERING                 1000
#define IDC_ARCHITECTURAL               1001
#define IDC_FEET                        1002
#define IDC_METRIC                      1003
#define IDC_INCHES                      1004
#define IDC_TRAP                        1005
#define IDC_TEXT                        1006
#define IDC_NORMAL                      1007
#define IDC_PAN                         1008
#define IDC_OVERVIEW                    1009
#define IDC_RATIO                       1010
#define IDC_X                           1011
#define IDC_Y                           1012
#define IDC_Z                           1013
#define IDC_TEXT_HEIGHT                 1014
#define IDC_PRECISION                   1015
#define IDC_TEXT_ROTATION               1016
#define IDC_PATH_RIGHT                  1017
#define IDC_PATH_LEFT                   1018
#define IDC_PATH_UP                     1019
#define IDC_PATH_DOWN                   1020
#define IDC_TEXT_EXP_FAC                1021
#define IDC_TEXT_SPACING                1022
#define IDC_TEXT_INCLIN                 1023
#define IDC_TEXT_ALIGN_HOR_LEFT         1024
#define IDC_TEXT_ALIGN_HOR_CEN          1025
#define IDC_TEXT_ALIGN_HOR_RIGHT        1026
#define IDC_TEXT_ALIGN_VER_BOT          1027
#define IDC_TEXT_ALIGN_VER_MID          1028
#define IDC_TEXT_ALIGN_VER_TOP          1029
#define IDC_FIL_AREA_HAT_ID             1030
#define IDC_FIL_AREA_HAT_X_SCAL         1031
#define IDC_FIL_AREA_HAT_Y_SCAL         1032
#define IDC_FIL_AREA_HAT_ROT_ANG        1033
#define IDC_WIDTH                       1034
#define IDC_DEPTH                       1035
#define IDC_LEFT                        1036
#define IDC_CENTER                      1037
#define IDC_RIGHT                       1038
#define IDC_MITERED                     1039
#define IDC_RADIAL                      1040
#define IDC_GEN_VANES                   1041
#define IDC_RADIUS_FACTOR               1042
#define IDC_BEST                        1043
#define IDC_VIEW_VPN_Z_ANG              1048
#define IDC_VIEW_VPN_X_ANG              1049
#define IDC_VIEW_DOP_Z_ANG              1052
#define IDC_VIEW_DOP_X_ANG              1053
#define IDC_VIEW_DIS_TO_TARGET          1054
#define IDC_FIX_SIZ                     1057
#define IDC_FIX_AX_TOL                  1058
#define IDC_USR_AX_INF_ANG              1063
#define IDC_USR_AX_Z_OFF_ANG            1064
#define IDC_USR_GRID_X_INT              1068
#define IDC_USR_GRID_Y_INT              1069
#define IDC_USR_GRID_Z_INT              1070
#define IDC_GRID_DOT_INT_X              1074
#define IDC_GRID_DOT_INT_Y              1075
#define IDC_GRID_DOT_INT_Z              1076
#define IDC_GRID_LN_INT_X               1077
#define IDC_GRID_LN_INT_Y               1078
#define IDC_GRID_LN_INT_Z               1079
#define IDC_GRID_PTS_DIS_ON             1080
#define IDC_GRID_LNS_DIS_ON             1081
#define IDC_GRID_SNAP_ON                1082
#define IDC_PROFILE                     1083
#define IDC_GEOMETRY_LIST               1087
#define IDC_DRWG_REP_DEL                1094
#define IDC_ANN_BUB_RAD                 1099
#define IDC_ANN_BUB_FACETS              1100
#define IDC_ANN_DEF_TXT                 1101
#define IDC_ANN_HOOK_RAD                1102
#define IDC_ANN_GAP_SPACE_FAC           1103
#define IDC_ANN_ARR_SIZ                 1104
#define IDC_ANN_ARR_TYP                 1105
#define IDC_COL_LIST                    1106
#define IDC_MORELESS                    1115
#define IDC_LAST                        1116
#define IDC_VIEW_NAME_LIST              1121
#define IDC_KEYPLAN_AREA                1124
#define IDC_LESS_AREA                   1125
#define IDC_SAVE                        1127
#define IDC_RECALL                      1128
#define IDC_LAY                         1138
#define IDC_DIR_LIST                    1149
#define IDC_METRIC_UNITS                1155
#define IDC_EDIT_OP_SIZING              1166
#define IDC_EDIT_OP_ROTATION            1170
#define IDC_EDIT_OP_SIZ_X               1171
#define IDC_EDIT_OP_SIZ_Y               1172
#define IDC_EDIT_OP_SIZ_Z               1173
#define IDC_EDIT_OP_ROT_X               1174
#define IDC_EDIT_OP_ROT_Y               1175
#define IDC_EDIT_OP_ROT_Z               1176
#define IDC_EDIT_OP_MIRRORING           1177
#define IDC_EDIT_OP_MIR_X               1178
#define IDC_EDIT_OP_MIR_Y               1179
#define IDC_EDIT_OP_MIR_Z               1180
#define IDC_TRAP_FILTER_PEN             1185
#define IDC_TRAP_FILTER_LINE            1186
#define IDC_TRAP_FILTER_ELEMENT         1187
#define IDC_TRAP_FILTER_PEN_ID          1188
#define IDC_TRAP_FILTER_ELEMENT_LIST    1190
#define IDC_SCALE                       1191
#define IDC_TRAP_FILTER_LINE_LIST       1192
#define IDC_NEAR                        1208
#define IDC_FAR                         1209
#define IDC_LIGHT_AMBIENT_RED           1210
#define IDC_L0_AMBIENT_RED              1211
#define IDC_L0_POSITION_X               1212
#define IDC_L0_POSITION_Z               1213
#define IDC_LIGHT_AMBIENT_GREEN         1214
#define IDC_LIGHT_AMBIENT_BLUE          1215
#define IDC_L0_AMBIENT_GREEN            1216
#define IDC_L0_AMBIENT_BLUE             1217
#define IDC_L0_SPECULAR_RED             1218
#define IDC_L0_SPECULAR_GREEN           1219
#define IDC_L0_SPECULAR_BLUE            1220
#define IDC_L0_DIFFUSE_RED              1221
#define IDC_L0_DIFFUSE_GREEN            1222
#define IDC_L0_DIFFUSE_BLUE             1223
#define IDC_FILL                        1230
#define IDC_CONSTRAINTS                 1231
#define IDC_TRACLOAK                    1239
#define IDC_TRAFUSE                     1241
#define IDC_LAYDELETE                   1242
#define IDC_LAYMELT                     1243
#define IDC_L0_POSITION_Y               1245
#define IDC_TRA                         1248
#define IDC_LAYRENAME                   1249
#define IDC_TRAEXCLUDE                  1250
#define IDC_TRAINCLUDE                  1251
#define IDC_LAYNEW                      1252
#define IDC_PENSTYLE                    1253
#define IDC_COLOR_ID                    1254
#define IDC_SEGS                        1256
#define IDC_LAYWORK                     1263
#define IDC_LAYACTIVE                   1264
#define IDC_LEFT_DOWN                   1273
#define IDC_EDIT1                       1274
#define IDC_LEFT_UP                     1276
#define IDC_RIGHT_DOWN                  1277
#define IDC_RIGHT_UP                    1278
#define IDC_ARC_3_POINT                 1278
#define IDC_ARC_CENTER_2_POINTS         1279
#define IDC_CURVE_SPLINE                1280
#define IDC_CURVE_FITTED                1281
#define IDC_MARKER_TYPE                 1282
#define IDC_PEN                         1283
#define IDC_LINE                        1284
#define IDC_NAME                        1285
#define IDC_MOD_FILL                    1292
#define IDC_MOD_PEN                     1293
#define IDC_MOD_LINE                    1294
#define IDC_MOD_NOTE                    1295
#define IDC_MOD_MARKER                  1296
#define IDC_LAYSTATIC                   1298
#define IDC_UP_ONE_LEVEL                1299
#define IDC_TRAOPEN                     1300
#define IDC_TRAMAP                      1302
#define IDC_TRAVIEW                     1304
#define IDC_LAYHIDDEN                   1305
#define IDC_FILE_NAME                   1307
#define IDC_NEW_FOLDER                  1308
#define IDC_DESCRIPTION                 1310
#define IDC_LAYER_PREVIEW               1312
#define IDC_SOLO                        1314
#define IDC_BLOCKS_LIST                 1315
#define IDC_REFERENCES                  1316
#define IDC_CHECK1                      1319
#define IDC_APPEND                      1320
#define IDC_INSERT                      1320
#define IDC_RADIO1                      1323
#define IDC_RADIO2                      1324
#define IDC_FORM                        1325
#define IDC_SHEET                       1325
#define IDC_PURGE                       1326
#define IDC_FULL                        1326
#define IDC_GET                         1327
#define IDC_HALF                        1327
#define IDC_QUARTER                     1328
#define IDC_FILES_EX                    1329
#define IDC_BLOCKS                      1330
#define IDC_LOAD                        1331
#define IDC_DISTANCE                    1332
#define IDC_LIST                        1334
#define IDC_TIC_SIZE                    1335
#define IDC_RISEDROP_RADIUS             1336
#define IDC_ANGLE                       1338
#define IDC_APPS                        1339
#define IDC_VIEW_ISO_LEFT               1340
#define IDC_VIEW_ISO_RIGHT              1341
#define IDC_VIEW_ISO_FRONT              1342
#define IDC_VIEW_ISO_BACK               1343
#define IDC_VIEW_ISO_ABOVE              1344
#define IDC_VIEW_ISO_UNDER              1345
#define IDC_DIAMETER                    1346
#define IDC_CENTERLINE                  1347
#define IDC_LOCAL_VIEWPOINT             1348
#define IDC_LIGHTING_ENABLED            1349
#define IDC_SEGMENT_TREE                1350
#define IDC_EXTRA_LIST_CTRL             1351
#define IDC_PENSTYLES                   1352
#define IDC_HEIGHT                      1354
#define IDC_FONT_NAME                   1355
#define IDC_PRP_Y                       1356
#define IDC_PRP_Z                       1357
#define IDC_TARGET_X                    1358
#define IDC_TARGET_Y                    1359
#define IDC_TARGET_Z                    1360
#define IDC_PRP_X                       1361
#define IDC_VPN_X                       1362
#define IDC_VPN_Y                       1363
#define IDC_VPN_Z                       1364
#define IDC_FONT                        1365
#define IDC_CURRENTVIEW                 1366
#define IDC_EXTENTS                     1367
#define IDC_TOFIT                       1368
#define IDC_RADIO_MARK_STYLE_0          1369
#define IDC_RADIO_MARK_STYLE_1          1370
#define IDC_RADIO_MARK_STYLE_2          1371
#define IDC_RADIO_MARK_STYLE_3          1372
#define IDC_CHECK2                      1373
#define IDC_RADIO_MARK_STYLE_4          1374
#define IDS_MSG_NO_DET_SEGS_IN_VIEW     3792
#define IDS_MSG_ZERO_LENGTH_STRING      3793
#define IDS_MSG_PRIM_ADDED_TO_DEL_SEGS  3794
#define IDS_SEG_DEL_TO_RESTORE          3795
#define IDS_MSG_BAD_PRIM_TYPE           3796
#define IDS_MSG_LAYER_IS_RESIDENT       3797
#define IDS_OPENFILE_FILTER             3798
#define IDS_OPENFILE_FILTER_TRACINGS    3799
#define IDS_OPENFILE_FILTER_PENCOLORS   3800
#define IDS_OPENFILE_FILTER_APPS        3801
#define IDS_OPENFILE_FILTER_BLOCKS      3802
#define IDS_MSG_VERSION_1_JOB_FILE      3803
#define IDS_MSG_TRACING_WRITE_FAILURE   3804
#define IDS_MSG_TRACING_OPEN_FAILURE    3805
#define IDS_MSG_SQRT_NEG                3806
#define IDS_MSG_DDE_INIT_FAILURE        3807
#define IDS_MSG_LAYER_NO_STATIC         3808
#define IDS_MSG_LAYER_NO_HIDDEN         3809
#define IDS_MSG_LAYER_NO_ACTIVE         3810
#define IDS_MSG_CONFIRM_CLOSE           3811
#define IDS_MSG_CONFIRM_EXIT            3812
#define IDS_LAYER_NOT_LOADED            3813
#define IDS_MSG_CONFIRM_BLANK           3814
#define IDS_MSG_LAYER_NO_DELETE_0       3815
#define IDS_MSG_LAYER_NO_DELETE_WORK    3816
#define IDS_MSG_LAYER_NO_RENAME_0       3817
#define IDS_MSG_PTS_COINCIDE            3818
#define IDS_MSG_PTS_COLINEAR            3819
#define IDS_MSG_LPD_NO_END_CAP_LOC      3820
#define IDS_MSG_LPD_NOT_DUCT_SEC        3821
#define IDS_MSG_LPD_UNK_TURN_DIR        3822
#define IDS_MSG_MEM_ALLOC_ERR           3823
#define IDS_MSG_SAVE_STATE_LIST_ERROR   3824
#define IDS_MSG_FILE_LOCKED             3825
#define IDS_MSG_CLIPBOARD_LOCKED        3826
#define IDS_MSG_FILE_NOT_OPEN           3827
#define IDS_MSG_FILE_NOT_FOUND          3828
#define IDS_MSG_SAVE_CHANGES            3829
#define IDS_MSG_DISPOSE_FIRST           3830
#define IDS_MSG_CLOSE_TRACING_FIRST     3831
#define IDS_MSG_SHADOW_FILE_CREATE_FAILURE 3832
#define IDS_MSG_FILE_TYPE_ERROR         3833
#define IDS_MSG_FILE_NOT_A_TRACING      3834
#define IDS_MSG_OPEN_TRACING_NO_CLOAK   3835
#define IDS_MSG_NOTHING_TO_SAVE         3836
#define IDS_MSG_FILE_SHADOWED_AS        3837
#define IDS_MSG_TRACING_SAVE_SUCCESS    3838
#define IDS_MSG_TOO_MANY_PTS            3839
#define IDS_SUBPROC_PIPE_SYMBOL_NAMES   3840
#define IDS_HOME_POINT_GO_NAMES         3841
#define IDS_HOME_POINT_SET_NAMES        3842
#define ID_OP0                          4112
#define ID_OP1                          4113
#define ID_OP2                          4114
#define ID_OP3                          4115
#define ID_OP4                          4116
#define ID_OP5                          4117
#define ID_OP6                          4118
#define ID_OP7                          4119
#define ID_OP8                          4120
#define ID_OP9                          4121
#define ID_MODE_ANNOTATE                4128
#define ID_MODE_CUT                     4129
#define ID_MODE_DIMENSION               4130
#define ID_MODE_DRAW                    4131
#define ID_MODE_DRAW2                   4132
#define ID_MODE_EDIT                    4133
#define ID_MODE_NODAL                   4134
#define ID_MODE_NODALR                  4135
#define ID_MODE_TRAP                    4136
#define ID_MODE_TRAPR                   4137
#define ID_MODE_FIXUP                   4138
#define ID_MODE_PRIM_EDIT               4139
#define ID_MODE_PRIM_MEND               4140
#define ID_MODE_SEG_EDIT                4141
#define ID_MODE_LPD                     4142
#define ID_MODE_POWER                   4143
#define ID_MODE_PIPE                    4144
#define ID_MODE_RLPD                    4145
#define ID_CURSOR_DEFAULT               4149
#define ID_CURSOR_SYMBOL                4150
#define ID_SETUP_UNITS                  4151
#define ID_VIEW_REFRESH                 4152
#define ID_SETUP_SCALE                  4153
#define ID_FILE_TRACING                 4159
#define ID_SETUP_NOTE                   4160
#define ID_RELATIVEMOVES_RIGHT          4163
#define ID_RELATIVEMOVES_UP             4164
#define ID_RELATIVEMOVES_LEFT           4165
#define ID_RELATIVEMOVES_DOWN           4166
#define ID_RELATIVEMOVES_IN             4167
#define ID_RELATIVEMOVES_OUT            4168
#define ID_RELATIVEMOVES_RIGHTROTATE    4169
#define ID_RELATIVEMOVES_UPROTATE       4170
#define ID_RELATIVEMOVES_LEFTROTATE     4171
#define ID_RELATIVEMOVES_DOWNROTATE     4172
#define ID_SEG_DELETE                   4173
#define ID_PRIM_SNAPTO                  4174
#define ID_PRIM_SNAPTOENDPOINT          4175
#define ID_SEG_INSERT                   4177
#define ID_SETUP_PENCOLOR               4179
#define ID_SETUP_DIMLENGTH              4182
#define ID_SETUP_DIMANGLE               4183
#define ID_SETUP_PENSTYLE               4184
#define IDM_RETURN                      4196
#define IDM_ESCAPE                      4197
#define ID_SEG_BREAK                    4254
#define ID_PRIM_BREAK                   4255
#define ID_PENS_REMOVEUNUSEDSTYLES      4260
#define ID_PENS_LOADCOLORS              4261
#define ID_PENS_UNLOADCOLORS            4262
#define ID_PENS_TRANSLATE               4263
#define ID_LAYERS_LOAD                  4265
#define ID_LAYERS_UNLOAD                4266
#define ID_LAYERS_REMOVEEMPTY           4267
#define ID_LAYERS_STATICALL             4268
#define ID_LAYERS_ACTIVEALL             4269
#define ID_BLOCKS_LOAD                  4271
#define ID_BLOCKS_UNLOAD                4272
#define ID_BLOCKS_REMOVEUNUSED          4273
#define ID_PENS_EDITSTYLES              4274
#define ID_TRACINGS_MAPALL              4276
#define ID_TRACINGS_VIEWALL             4277
#define ID_TRACINGS_CLOAKALL            4278
#define ID_PENS_EDITCOLORS              4279
#define ID_PENS_USEDEFAULTS             4280
#define ID_SETUP_SAVEPOINT              4302
#define ID_SETUP_GOTOPOINT              4303
#define ID_FILE_PLOT_QUARTER            4304
#define ID_MAINTENANCE_REMOVEDUPLICATES 4308
#define ID_MAINTENANCE_REMOVEEMPTYNOTES 4311
#define ID_MAINTENANCE_REMOVEEMPTYSEGMENTS 4312
#define ID_FILE                         4319
#define ID_HELP_CONTENTS                4321
#define ID_CLEAR_VIEWEDTRACINGS         4322
#define ID_CLEAR_WORKINGLAYER           4323
#define ID_CLEAR_MAPPEDTRACINGS         4324
#define ID_RESET_ALL                    4325
#define ID_SETUP_FILL_HOLLOW            4326
#define ID_SETUP_FILL_SOLID             4327
#define ID_SETUP_FILL_PATTERN           4328
#define ID_SETUP_FILL_HATCH             4329
#define ID_PRIM_GOTOCENTERPOINT         4334
#define ID_MODE_REVISE                  4335
#define ID_MODE_LETTER                  4336
#define ID_PRIM_PERPJUMP                4337
#define ID_PRIM_MODIFY_ATTRIBUTES       4338
#define ID_HELP_KEY                     4339
#define ID_FILE_PRINTCURRENTVIEW        4341
#define ID_VIEW_ODOMETER                4342
#define ID_3DVIEWS_TOP                  4344
#define ID_3DVIEWS_BOTTOM               4345
#define ID_3DVIEWS_FRONT                4346
#define ID_3DVIEWS_BACK                 4347
#define ID_3DVIEWS_LEFT                 4348
#define ID_3DVIEWS_RIGHT                4349
#define ID_3DVIEWS_ISOMETRIC            4352
#define ID_3DVIEWS_AXONOMETRIC          4353
#define ID_3DVIEWS_OBLIQUE              4354
#define ID_3DVIEWS_PERSPECTIVE          4355
#define ID_VIEW_WIREFRAME               4356
#define ID_SEG_DELETELAST               4376
#define ID_PRIM_EXTRACTNUM              4377
#define ID_PRIM_EXTRACTSTR              4378
#define ID_EDIT_TRAPCOPY                4380
#define ID_EDIT_TRAPCUT                 4381
#define ID_EDIT_TRAPPASTE               4382
#define ID_MODE_SEGEDIT                 4388
#define ID_FILE_RUN                     4395
#define ID_VIEW_RENDERED                4408
#define ID_VIEW_SOLID                   4409
#define ID_PRIM_DELETE                  4417
#define ID_VIEW_PARAMETERS              4436
#define ID_EDIT_IMAGETOCLIPBOARD        4438
#define ID_EDIT_TRACE                   4440
#define ID_SETUP_MOUSEBUTTONS           4450
#define ID_CURSOR_CROSSHAIR             4451
#define ID_SETUP_OPTIONS_DRAW           4508
#define ID_SETUP_OPTIONS_EDIT           4509
#define ID_SETUP_OPTIONS_ANNOTATE       4510
#define ID_SETUP_OPTIONS_2LINE          4511
#define ID_SETUP_OPTIONS_FIXUP          4512
#define ID_SETUP_OPTIONS_DIMENSION      4513
#define ID_WINDOW_PAN_LEFT              4530
#define ID_WINDOW_PAN_UP                4532
#define ID_WINDOW_PAN_DOWN              4533
#define ID_VIEW_ZOOM                    4550
#define ID_WINDOW_ZOOMIN                4551
#define ID_WINDOW_ZOOMOUT               4552
#define ID_WINDOW_NORMAL                4553
#define ID_WINDOW_PAN                   4554
#define ID_TRACING_MAP                  4556
#define ID_TRACING_VIEW                 4557
#define ID_TRACING_CLOAK                4558
#define ID_TRACING_FUSE                 4559
#define ID_LAYER_WORK                   4560
#define ID_LAYER_ACTIVE                 4561
#define ID_LAYER_STATIC                 4562
#define ID_LAYER_HIDDEN                 4563
#define ID_LAYER_MELT                   4564
#define ID_LAYER_LAYERNAME              4565
#define ID_TRACING_TRACINGNAME          4566
#define ID_TRACING_OPEN                 4567
#define ID_EDIT_TRAPQUIT                4569
#define ID_FILE_PLOT_FULL               4570
#define ID_FILE_PLOT_HALF               4571
#define ID_EDIT_TRAPWORK                4572
#define ID_EDIT_TRAPWORKANDACTIVE       4574
#define ID_TRAPCOMMANDS_ADDSEGMENTS     4575
#define ID_EDIT_TRAPDELETE              4577
#define ID_TRAPCOMMANDS_HIGHLIGHT       4580
#define ID_TRAPCOMMANDS_COMPRESS        4581
#define ID_TRAPCOMMANDS_EXPAND          4582
#define ID_TRAPCOMMANDS_INVERT          4583
#define ID_TRAPCOMMANDS_SQUARE          4584
#define ID_TRAPCOMMANDS_QUERY           4585
#define ID_TRAPCOMMANDS_FILTER          4586
#define ID_FILE_MANAGE                  4587
#define ID_TRAPCOMMANDS_BLOCK           4588
#define ID_TRAPCOMMANDS_UNBLOCK         4590
#define ID_SEG_EXCHANGE                 4591
#define ID_EDIT_SEGTOWORK               4593
#define ID_VIEW_PENWIDTHS               4594
#define ID_SETUP_CONSTRAINTS_AXIS       4599
#define ID_SETUP_CONSTRAINTS_GRID       4600
#define ID_VIEW_TRUETYPEFONTS           4605
#define ID_VIEW_STATEINFORMATION        4606
#define ID_CLEAR_ACTIVELAYERS           4607
#define ID_CLEAR_ALLLAYERS              4608
#define ID_CLEAR_ALLTRACINGS            4609
#define ID_EDIT_CF_SEGMENTS             4616
#define ID_EDIT_CF_TEXT                 4618
#define ID_EDIT_CF_IMAGE                4619
#define ID_VIEW_LIGHTING                4621
#define ID_WINDOW_PAN_RIGHT             4623
#define ID_WINDOW_BEST                  4624
#define ID_VIEW_WINDOW                  4625
#define ID_WINDOW_LAST                  4626
#define ID_WINDOW_SHEET                 4627
#define ID_CAMERA_ROTATELEFT            4629
#define ID_CAMERA_ROTATERIGHT           4630
#define ID_CAMERA_ROTATEUP              4631
#define ID_CAMERA_ROTATEDOWN            4632
#define ID_FILE_QUERY                   4633
#define ID_RELATIVEMOVES_ENG_RIGHT      4634
#define ID_RELATIVEMOVES_ENG_DOWN       4635
#define ID_RELATIVEMOVES_ENG_IN         4636
#define ID_RELATIVEMOVES_ENG_OUT        4637
#define ID_RELATIVEMOVES_ENG_LEFT       4638
#define ID_RELATIVEMOVES_ENG_LEFTROTATE 4639
#define ID_RELATIVEMOVES_ENG_RIGHTROTATE 4640
#define ID_RELATIVEMOVES_ENG_DOWNROTATE 4641
#define ID_RELATIVEMOVES_ENG_UP         4642
#define ID_RELATIVEMOVES_ENG_UPROTATE   4643
#define ID_SHIFT_RETURN                 4645
#define ID_SETUP_MARKSTYLE              4646

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         4647
#define _APS_NEXT_CONTROL_VALUE         1374
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
